# Generated by Django 3.2.19 on 2023-06-03 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technique',
            name='occupation',
        ),
    ]
