# Generated by Django 3.2.19 on 2023-06-04 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='type',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, to='plans.type'),
            preserve_default='True',
        ),
    ]
