# Generated by Django 3.2.19 on 2023-06-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20230606_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('jobtype', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='type',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='plan',
            name='jobtype',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, to='plans.jobtype'),
            preserve_default='True',
        ),
    ]
