# Generated by Django 3.2.19 on 2023-06-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_auto_20230604_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
