# Generated by Django 3.2.19 on 2023-06-04 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_auto_20230604_0159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanType',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='plantype',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='plantype',
            new_name='type',
        ),
    ]
