# Generated by Django 3.2.19 on 2023-06-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_auto_20230611_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='occupation',
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
    ]
