# Generated by Django 3.2.19 on 2023-06-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_auto_20230604_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='goal',
        ),
    ]
