# Generated by Django 3.2.19 on 2023-06-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_remove_plan_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('type', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
