# Generated by Django 3.2.19 on 2023-06-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_auto_20230615_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='level',
        ),
    ]
