# Generated by Django 3.2.19 on 2023-06-04 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_auto_20230604_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='goal',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.goal'),
        ),
    ]
