# Generated by Django 3.2.19 on 2023-06-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_remove_plan_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
