# Generated by Django 3.2.19 on 2023-06-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_alter_plan_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='goal',
        ),
    ]
