# Generated by Django 3.2.19 on 2023-06-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_remove_plan_goal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
