# Generated by Django 3.2.19 on 2023-06-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplan',
            name='original_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='orderplan',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
