# Generated by Django 3.2.19 on 2023-06-10 20:22

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20230610_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplan',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
