# Generated by Django 3.2.19 on 2023-06-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_orderplan_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplan',
            name='grand_total',
        ),
    ]
