# Generated by Django 3.2.19 on 2023-08-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_orderplan_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplan',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
