# Generated by Django 3.2.19 on 2023-06-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffw', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
    ]
