# Generated by Django 3.2.19 on 2023-06-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffw', '0004_plan_technique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='technique',
        ),
        migrations.RemoveField(
            model_name='technique',
            name='occupation',
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Technique',
        ),
    ]
